services:
  uvr-webui:
    build: .
    ports:
      - "7862:7860"  # Mapowanie portu hosta (7862) na port kontenera (7860)
    volumes:
      - ./models:/opt/uvr-webui/models
      - ./outputs:/opt/uvr-webui/outputs
    entrypoint: ["python", "app.py", "--listen-port", "7860"]
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
