services:
  uvr-webui:
    build: .
    entrypoint: ["python", "app.py", "--server_port", "7860", "--server_name", "0.0.0.0", "--username", "user", "--password", "password"]
    ports:
      - "7862:7860" 
    volumes:
      - ./models:/opt/uvr-webui/models
      - ./outputs:/opt/uvr-webui/outputs
      - ./inputs:/opt/uvr-webui/inputs
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
