services:
  app:
    build: .
    entrypoint: ["python", "app.py", "--server_port", "7860", "--server_name", "0.0.0.0"]
    ports:
      - "7860:7860"
    volumes:
      - ./models:/UVR5-UI-Docker/models
      - ./inputs:/UVR5-UI-Docker/inputs
      - ./outputs:/UVR5-UI-Docker/outputs
    tty: true
    stop_signal: SIGKILL
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
