FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04


# Install Python and other necessary packages
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        python3.10 \
        python3-pip \
        ffmpeg \
        wget \
        curl \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up working directory
WORKDIR /opt/uvr-webui

COPY . .

# Upgrade pip and install requirements
RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install -r requirements.txt

# Set environment variables
ENV PATH="/opt/uvr-webui/env/bin:$PATH"
ENV PYTHONUNBUFFERED=1

# Define volumes
VOLUME [ "/opt/uvr-webui/modelss", "/opt/uvr-webui/inputs", "/opt/uvr-webui/outputs" ]

# Expose the web UI port
EXPOSE 7860

# Start the application
CMD ["python3", "app.py"]
